function Publish-CompliancePolicy {
    <#
    .SYNOPSIS
        Deploys a compliance package to Intune via Microsoft Graph API.
    .DESCRIPTION
        Uploads the detection script and creates a custom compliance policy in Intune.
        Requires Microsoft.Graph.Authentication module and appropriate permissions.
    .PARAMETER DetectionScriptPath
        Path to the generated detection script (.ps1).
    .PARAMETER RulesJsonPath
        Path to the generated compliance rules JSON file.
    .PARAMETER PolicyName
        Display name for the compliance policy in Intune.
    .PARAMETER PolicyDescription
        Description for the compliance policy.
    .PARAMETER Update
        If a policy with the same name exists, update it instead of creating new.
    .EXAMPLE
        Publish-CompliancePolicy -DetectionScriptPath './output/Detection.ps1' -RulesJsonPath './output/Rules.json' -PolicyName 'W11 25H2 Baseline'
    #>
    [CmdletBinding(SupportsShouldProcess)]
    [OutputType([PSCustomObject])]
    param(
        [Parameter(Mandatory)]
        [ValidateScript({ Test-Path $_ -PathType Leaf })]
        [string]$DetectionScriptPath,

        [Parameter(Mandatory)]
        [ValidateScript({ Test-Path $_ -PathType Leaf })]
        [string]$RulesJsonPath,

        [Parameter()]
        [string]$PolicyName = 'GPOBaselineForge Compliance',

        [Parameter()]
        [string]$PolicyDescription = 'Custom compliance policy generated by GPOBaselineForge from Microsoft security baseline.',

        [Parameter()]
        [switch]$Update
    )

    # Ensure Graph connection
    $connected = Connect-BaselineForgeGraph
    if (-not $connected) { return }

    # Read and encode detection script
    $scriptContent = Get-Content -Path $DetectionScriptPath -Raw
    $scriptBase64 = [Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes($scriptContent))

    # Read rules JSON
    $rulesContent = Get-Content -Path $RulesJsonPath -Raw

    # Check for existing script with same name
    if ($Update) {
        Write-Verbose "Checking for existing compliance script '$PolicyName'..."
        $existingScripts = Invoke-MgGraphRequest -Method GET `
            -Uri 'https://graph.microsoft.com/beta/deviceManagement/deviceComplianceScripts' `
            -ErrorAction Stop

        $existingScript = $existingScripts.value | Where-Object { $_.displayName -eq "$PolicyName - Detection" }
    }

    # Upload or update detection script
    $scriptBody = @{
        displayName              = "$PolicyName - Detection"
        description              = "Detection script for $PolicyName. Auto-generated by GPOBaselineForge."
        publisher                = 'GPOBaselineForge'
        detectionScriptContent   = $scriptBase64
        runAsAccount             = 'system'
        enforceSignatureCheck    = $false
        runAs32BitOn64BitSystem  = $false
    }

    if ($Update -and $existingScript) {
        $scriptId = $existingScript.id
        if ($PSCmdlet.ShouldProcess("Script '$PolicyName - Detection' (ID: $scriptId)", 'Update detection script')) {
            Write-Verbose "Updating existing detection script $scriptId..."
            $null = Invoke-MgGraphRequest -Method PATCH `
                -Uri "https://graph.microsoft.com/beta/deviceManagement/deviceComplianceScripts/$scriptId" `
                -Body ($scriptBody | ConvertTo-Json -Depth 5) `
                -ContentType 'application/json'
        }
    }
    else {
        if ($PSCmdlet.ShouldProcess("Intune tenant", "Create detection script '$PolicyName - Detection'")) {
            Write-Verbose 'Creating new detection script...'
            $scriptResult = Invoke-MgGraphRequest -Method POST `
                -Uri 'https://graph.microsoft.com/beta/deviceManagement/deviceComplianceScripts' `
                -Body ($scriptBody | ConvertTo-Json -Depth 5) `
                -ContentType 'application/json'
            $scriptId = $scriptResult.id
            Write-Verbose "Detection script created with ID: $scriptId"
        }
    }

    # Return summary
    [PSCustomObject]@{
        PSTypeName        = 'BaselineForge.PublishedPolicy'
        PolicyName        = $PolicyName
        ScriptId          = $scriptId
        Action            = if ($Update -and $existingScript) { 'Updated' } else { 'Created' }
        DetectionScript   = "$PolicyName - Detection"
        RulesJsonIncluded = $true
        Note              = 'Upload the rules JSON manually in Intune portal under the compliance policy settings, or use the Settings Catalog API to complete the linkage.'
    }
}
