function New-DetectionScript {
    <#
    .SYNOPSIS
        Generates an Intune custom compliance detection script.
    .DESCRIPTION
        Creates a self-contained PowerShell script that checks baseline settings
        on endpoints and outputs a JSON hash for Intune custom compliance evaluation.
    .PARAMETER Setting
        Array of classified BaselineForge.Setting objects to check.
    .PARAMETER BaselineName
        Human-readable baseline name for the script header comment.
    #>
    [CmdletBinding()]
    [OutputType([string])]
    param(
        [Parameter(Mandatory)]
        [PSCustomObject[]]$Setting,

        [Parameter()]
        [string]$BaselineName = 'Microsoft Security Baseline'
    )

    $sb = [System.Text.StringBuilder]::new()

    # Header
    $null = $sb.AppendLine("# Auto-generated by GPOBaselineForge on $(Get-Date -Format 'yyyy-MM-dd')")
    $null = $sb.AppendLine("# Baseline: $BaselineName")
    $null = $sb.AppendLine("# Settings: $($Setting.Count)")
    $null = $sb.AppendLine('#')

    # Count by type for header comment
    $typeCounts = $Setting | Group-Object SettingType | ForEach-Object { "$($_.Name): $($_.Count)" }
    $null = $sb.AppendLine("# Types: $($typeCounts -join ', ')")

    $sevCounts = $Setting | Group-Object Severity | ForEach-Object { "$($_.Name): $($_.Count)" }
    $null = $sb.AppendLine("# Severity: $($sevCounts -join ', ')")
    $null = $sb.AppendLine('')
    $null = $sb.AppendLine('$results = @{}')
    $null = $sb.AppendLine('')

    # Group settings by type for efficient generation
    $byType = $Setting | Group-Object SettingType

    foreach ($group in $byType) {
        $null = $sb.AppendLine("# --- $($group.Name) Checks ($($group.Count)) ---")

        switch ($group.Name) {
            'Registry' {
                foreach ($s in $group.Group) {
                    # Convert HKLM\path to HKLM:\path for PowerShell
                    $psPath = $s.RegistryKey -replace '^HKLM\\', 'HKLM:\' -replace '^HKU\\', 'HKU:\'
                    $escapedPath = $psPath.Replace("'", "''")
                    $escapedName = $s.ValueName.Replace("'", "''")

                    # Use type-appropriate sentinel: -1 for numeric types (Int64 rules),
                    # 'NOT_FOUND' for string types — prevents Intune error 65010
                    $notFoundValue = if ($s.DataType -in 'REG_DWORD', 'REG_QWORD') { '-1' } else { "'NOT_FOUND'" }

                    $null = $sb.AppendLine("try {")
                    $null = $sb.AppendLine("    `$v = Get-ItemProperty -Path '$escapedPath' -Name '$escapedName' -ErrorAction Stop")
                    $null = $sb.AppendLine("    `$results['$($s.Id)'] = `$v.'$escapedName'")
                    $null = $sb.AppendLine("} catch { `$results['$($s.Id)'] = $notFoundValue }")
                }
            }
            'AuditPolicy' {
                # Run auditpol once and parse all subcategories
                $null = $sb.AppendLine('try {')
                $null = $sb.AppendLine('    $auditRaw = auditpol /get /category:* /r 2>$null')
                $null = $sb.AppendLine('    $auditCsv = $auditRaw | ConvertFrom-Csv')
                $null = $sb.AppendLine('} catch { $auditCsv = @() }')

                foreach ($s in $group.Group) {
                    $subcat = $s.ValueName.Replace("'", "''")
                    $null = $sb.AppendLine("`$row = `$auditCsv | Where-Object { `$_.Subcategory -eq '$subcat' } | Select-Object -First 1")
                    $null = $sb.AppendLine("if (`$row) { `$results['$($s.Id)'] = [int]`$row.'Setting Value' } else { `$results['$($s.Id)'] = -1 }")
                }
            }
            'PrivilegeRight' {
                # Export secedit once for privilege rights
                $null = $sb.AppendLine('$seceditPath = "$env:TEMP\baselineforge_secedit.inf"')
                $null = $sb.AppendLine('try {')
                $null = $sb.AppendLine('    $null = secedit /export /cfg $seceditPath /quiet 2>$null')
                $null = $sb.AppendLine('    $seceditContent = Get-Content -Path $seceditPath -ErrorAction Stop')
                $null = $sb.AppendLine('} catch { $seceditContent = @() }')
                $null = $sb.AppendLine('finally { Remove-Item -Path $seceditPath -Force -ErrorAction SilentlyContinue }')

                foreach ($s in $group.Group) {
                    $privName = $s.ValueName
                    $null = $sb.AppendLine("`$line = `$seceditContent | Where-Object { `$_ -match '^$privName\s*=' } | Select-Object -First 1")
                    $null = $sb.AppendLine("if (`$line -and `$line -match '=\s*(.*)') { `$results['$($s.Id)'] = `$Matches[1].Trim() } else { `$results['$($s.Id)'] = '' }")
                }
            }
            'SystemAccess' {
                # Reuse secedit output if already exported, otherwise export
                $null = $sb.AppendLine('if (-not $seceditContent) {')
                $null = $sb.AppendLine('    $seceditPath = "$env:TEMP\baselineforge_secedit.inf"')
                $null = $sb.AppendLine('    try {')
                $null = $sb.AppendLine('        $null = secedit /export /cfg $seceditPath /quiet 2>$null')
                $null = $sb.AppendLine('        $seceditContent = Get-Content -Path $seceditPath -ErrorAction Stop')
                $null = $sb.AppendLine('    } catch { $seceditContent = @() }')
                $null = $sb.AppendLine('    finally { Remove-Item -Path $seceditPath -Force -ErrorAction SilentlyContinue }')
                $null = $sb.AppendLine('}')

                foreach ($s in $group.Group) {
                    $policyKey = $s.ValueName
                    # Use -1 sentinel for numeric SystemAccess settings, 'NOT_FOUND' for string
                    $notFoundValue = if ($s.ExpectedValue -is [int] -or $s.ExpectedValue -match '^\d+$') { '-1' } else { "'NOT_FOUND'" }
                    $null = $sb.AppendLine("`$line = `$seceditContent | Where-Object { `$_ -match '^$policyKey\s*=' } | Select-Object -First 1")
                    $null = $sb.AppendLine("if (`$line -and `$line -match '=\s*(.*)') { `$results['$($s.Id)'] = `$Matches[1].Trim() } else { `$results['$($s.Id)'] = $notFoundValue }")
                }
            }
            'ServiceConfig' {
                foreach ($s in $group.Group) {
                    $svcName = $s.ValueName.Replace("'", "''")
                    $null = $sb.AppendLine("try {")
                    $null = $sb.AppendLine("    `$svc = Get-Service -Name '$svcName' -ErrorAction Stop")
                    $null = $sb.AppendLine("    `$results['$($s.Id)'] = [int]`$svc.StartType")
                    $null = $sb.AppendLine("} catch { `$results['$($s.Id)'] = -1 }")
                }
            }
        }

        $null = $sb.AppendLine('')
    }

    # Output — Intune requires JSON to stdout
    $null = $sb.AppendLine('# Output results as JSON (Intune custom compliance requirement)')
    $null = $sb.AppendLine('$results | ConvertTo-Json -Compress')

    return $sb.ToString()
}
